### ISSUE TITLE
brs-js uploaded to npm has a left over "debug" directory that takes up a lot of space

### ISSUE THREAD

**Issue by foxydevloper** [Meshiest/brs-js#16]
I'm sure it was left over when publishing to npm, it makes this package take up 19 mb on disk from .brs files alone
https://www.npmjs.com/package/brs-js?activeTab=explore
![image](https://user-images.githubusercontent.com/12120644/225816775-a3b30975-b6dc-46c4-b4af-651cf6885245.png)

**Comment by Meshiest** [comment]
that is an accident 😳

**Comment by Meshiest** [comment]
it's already in the `.npmignore` 🤔 https://github.com/Meshiest/brs-js/blob/master/.npmignore#L2

**Comment by Meshiest** [comment]
it can't have `./`

**Comment by Meshiest** [comment]
fixed in 2.0.14
